# Based on ./gatekeeper-operator/bundle.Dockerfile
FROM registry.redhat.io/ubi9/ubi@sha256:dec374e05cc13ebbc0975c9f521f3db6942d27f8ccdf06b180160490eef8bdbc AS builder

RUN dnf install -y skopeo jq python3 python3-pip && \
    pip3 install ruamel.yaml

# Use a new stage to enable caching of the package installations for local development
# Automating bundle reference updates via Konflux requires us to maintain our own CSV file
COPY ./bundle-hack/ .
COPY limitador-operator/bundle/manifests /manifests/
RUN rm /manifests/limitador-operator.clusterserviceversion.yaml
COPY ./downstream-conversion/bundle/manifests/limitador-operator.clusterserviceversion.yaml /manifests
COPY ./downstream-conversion/bundle/metadata /metadata/
RUN chmod +x update_bundle.sh && ./update_bundle.sh

FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=limitador-operator
LABEL operators.operatorframework.io.bundle.channels.v1=alpha
LABEL operators.operatorframework.io.bundle.channel.default.v1=alpha

LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL version="1.2.0" \
      summary="Enables rate limiting for Gateways and applications in a Gateway API network" \
      name="Limitador Operator Bundle" \
      description="Enables rate limiting for Gateways and applications in a Gateway API network" \
      io.k8s.display-name="Limitador Operator metadata" \
      io.k8s.description="Enables rate limiting for Gateways and applications in a Gateway API network" \
      io.openshift.expose-services="" \
      io.openshift.tags="api" \
      url="" \
      distribution-scope="public" \
      release="1.2.0" \
      url="" \
      com.redhat.component="Red Hat Connectivity Link Operator Bundle" \
      vendor="Red Hat, Inc."

# Copy files to locations specified by labels.
COPY --from=builder /manifests /manifests/
COPY --from=builder /metadata /metadata/
COPY limitador-operator/bundle/tests/scorecard /tests/scorecard/
