FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=limitador-operator
LABEL operators.operatorframework.io.bundle.channels.v1=alpha
LABEL operators.operatorframework.io.bundle.channel.default.v1=alpha

LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL version="1.2.0" \
      summary="Enables rate limiting for Gateways and applications in a Gateway API network" \
      name="Limitador Operator Bundle" \
      description="Enables rate limiting for Gateways and applications in a Gateway API network" \
      io.k8s.display-name="Limitador Operator metadata" \
      io.k8s.description="Enables rate limiting for Gateways and applications in a Gateway API network" \
      io.openshift.expose-services="" \
      io.openshift.tags="api" \
      url="" \
      distribution-scope="public" \
      release="1.2.0" \
      url="" \
      com.redhat.component="Red Hat Connectivity Link Operator Bundle" \
      vendor="Red Hat, Inc."

# Copy files to locations specified by labels.
COPY /bundle/manifests /manifests/
COPY /bundle/metadata /metadata/
COPY limitador-operator/bundle/tests/scorecard /tests/scorecard/
